Add new image position field and necessary styling to Image backgroun…
morpht/modifiers_pack pull request #2
Opened 2017-09-10 13:34 UTC by petrillek

I've created this update to allow us to position background images.

TBD:
As this is adding new field we probably need to provide an update function.

2017-10-20 13:50 UTC, kybersoft requested changes
I think you have bad path for first file inside commit `docroot/sites/start/config/field.field.paragraph.image_modifier.field_image_position.yml` and I pointed on few requested changes - could you please fix them?

2017-10-20 13:50 UTC, kybersoft commented on modules/modifiers_bg_image/src/Plugin/modifiers/ImageBgModifier.php
Please remove this empty line :-)

2017-10-20 13:50 UTC, kybersoft commented on modules/modifiers_bg_image/src/Plugin/modifiers/ImageBgModifier.php
> +        $css['all'][$selector][] = 'background-position:' . $position;
We should use `$media` instead of `all`.

2018-03-05 21:15 UTC, petrillek commented
I added test for the new code and fixed a small bug in the module.

2018-03-06 18:44 UTC, kybersoft approved these changes
Nice work, thank you Petr!

2018-03-06 18:52 UTC, merged