Issue2916499
morpht/modifiers_pack pull request #5
Opened 2017-10-16 19:55 UTC by petrillek

Linear Gradient and Custom linear gradient modifiers are ready. 
Please review @kybersoft. :)

2017-10-20 13:29 UTC, kybersoft requested changes
Thank you Petr for great work! Please process these small  fixes.

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_custom_linear_gradient/README.md
> + along a customizable direction. If only one color is provided it will be set
These empty spaces at the line start (2x) are not needed (also inside modifiers_linear_gradient), please remove them.

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_custom_linear_gradient/modifiers_custom_linear_gradient.info.yml
> +  - modifiers
Dependencies need to have prefix, you can copy them from modifiers_custom_colors.info.yml.

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_linear_gradient/modifiers_linear_gradient.info.yml
> +  - modifiers
Dependencies need to have prefix, you can copy them from modifiers_colors.info.yml.

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_custom_linear_gradient/modifiers_custom_linear_gradient.info.yml
> +  - taxonomy
Taxonomy is not dependency of modifiers_custom_linear_gradient module, only modifiers_linear_gradient.

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_custom_linear_gradient/src/Plugin/modifiers/CustomLinearGradientModifier.php
> + * Provides a Modifier to set the linear gradient on an element using custom colors.
This line exceeds 80 characters, please shorten that - phpcs need short description on single line. I would stay with "Provides a Modifier to set the linear gradient on an element."

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_linear_gradient/src/Plugin/modifiers/LinearGradientModifier.php
> + * Provides a Modifier to set the linear gradient on an element using custom colors.
This line exceeds 80 characters, please shorten that - phpcs need short description on single line. I would stay with "Provides a Modifier to set the linear gradient on an element."

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_linear_gradient/src/Plugin/modifiers/LinearGradientModifier.php
> +      $attributes['class'][] = 'modifiers-has-background';
Please insert `$direction = '';` and one empty line right after this line.

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_linear_gradient/src/Plugin/modifiers/LinearGradientModifier.php
> +        $css[$media][$selector][] = 'background:linear-gradient(' . $direction . implode(',', $config['l_gradient_colors']) . ')';
Insert line break right after `'background:linear-gradient('`.

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_linear_gradient/src/Plugin/modifiers/LinearGradientModifier.php
> +      if (count($config['l_gradient_colors']) == 1) {
Please use "===".

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_custom_linear_gradient/src/Plugin/modifiers/CustomLinearGradientModifier.php
> +      $attributes['class'][] = 'modifiers-has-background';
Please insert `$direction = '';` and one empty line right after this line.

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_custom_linear_gradient/src/Plugin/modifiers/CustomLinearGradientModifier.php
> +      if (count($config['cl_gradient_colors']) == 1) {
Please use "===".

2017-10-20 13:29 UTC, kybersoft commented on modules/modifiers_custom_linear_gradient/src/Plugin/modifiers/CustomLinearGradientModifier.php
> +        $css[$media][$selector][] = 'background:linear-gradient(' . $direction . implode(',', $config['cl_gradient_colors']) . ')';
Insert line break right after `'background:linear-gradient('`.

2017-10-23 09:06 UTC, petrillek commented
Thanks for the review @kybersoft . 
Changes have been done.

2017-10-23 12:00 UTC, kybersoft approved these changes

2017-10-23 12:05 UTC, kybersoft commented
That looks much better, thank you @petrillek.
I checked also config files and there are some weird dependencies (`- ds` and `- workbench_moderation`) - can we get rid of them?

2017-10-23 12:11 UTC, kybersoft commented
These 3 files should be reexported without "ds" and "workbench_moderation" modules:
- core.entity_view_display.paragraph.custom_linear_gradient_modifier.default.yml
- core.entity_form_display.paragraph.custom_linear_gradient_modifier.default.yml
- core.entity_form_display.paragraph.linear_gradient_modifier.default.yml

2017-10-23 13:21 UTC, petrillek commented
Another itteration for you. ;) @kybersoft

2017-10-23 13:44 UTC, kybersoft commented
Tested and everything is working correctly, thanks. Going to merge :+1:

2017-10-23 14:21 UTC, merged